import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("meetings", "routes/meetings.tsx"),
  route("meetings/:id", "routes/meeting-detail.tsx"),
  route("meetings/:id/explorer", "routes/meeting-explorer.tsx"),
  route("meetings/:id/documents", "routes/meeting-documents.tsx"),
  route("meetings/:id/documents/:docId", "routes/document-viewer.tsx"),
  route("people", "routes/people.tsx"),
  route("participants", "routes/participants.tsx"),
  route("people/:id", "routes/person-profile.tsx"),
  route("people/:id/votes", "routes/person-votes.tsx"),
  route("people/:id/proposals", "routes/person-proposals.tsx"),

  route("matters", "routes/matters.tsx"),
  route("matters/:id", "routes/matter-detail.tsx"),
  route("bylaws", "routes/bylaws.tsx"),
  route("bylaws/:id", "routes/bylaw-detail.tsx"),
  route("elections", "routes/elections.tsx"),
  route("elections/:id", "routes/election-detail.tsx"),
  route("search", "routes/search.tsx"),
  route("ask", "routes/ask.tsx"),
  route("about", "routes/about.tsx"),
  route("alignment", "routes/alignment.tsx"),
  route("compare", "routes/compare.tsx"),
  route("login", "routes/login.tsx"),
  route("signup", "routes/signup.tsx"),
  route("logout", "routes/logout.tsx"),
  route("settings", "routes/settings.tsx"),
  route("settings/api-keys", "routes/settings.api-keys.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("speaker-alias", "routes/speaker-alias.tsx"),
  route("admin/people", "routes/admin-people.tsx"),
  route("admin/pipeline", "routes/admin-pipeline.tsx"),
  route("admin/pipeline/jobs/:id", "routes/admin-pipeline-job.tsx"),

  route("onboarding", "routes/onboarding.tsx"),

  // API routes
  route("api/ask", "routes/api.ask.tsx"),
  route("api/geocode", "routes/api.geocode.tsx"),
  route("api/digest", "routes/api.digest.tsx"),
  route("api/subscribe", "routes/api.subscribe.tsx"),
  route("api/report-video-failure", "routes/api.report-video-failure.ts"),
  route("api/bylaws/:id/download", "routes/api.bylaws.$id.download.tsx"),
  route("api/intel/:id", "routes/api.intel.tsx"),
  route("api/vimeo-url", "routes/api.vimeo-url.ts"),
  route("api/search", "routes/api.search.tsx"),
  route("api/og-image", "routes/api.og-image.tsx"),
] satisfies RouteConfig;
