-- Pipeline ops console: source inventory, job queue, and run events.

CREATE TABLE IF NOT EXISTS source_meetings (
    id bigint generated by default as identity primary key,
    municipality_id bigint REFERENCES municipalities(id) ON DELETE CASCADE NOT NULL,
    source_type text NOT NULL,
    source_id text NOT NULL,
    meeting_date date NOT NULL,
    title text NOT NULL,
    meeting_type text,
    source_url text,
    video_url text,
    archive_path text,
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'discovered',
    last_error text,
    discovered_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_seen_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    ingested_meeting_id bigint REFERENCES meetings(id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (municipality_id, source_type, source_id)
);

DROP TRIGGER IF EXISTS set_timestamp_source_meetings ON source_meetings;
CREATE TRIGGER set_timestamp_source_meetings
    BEFORE UPDATE ON source_meetings
    FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE INDEX IF NOT EXISTS idx_source_meetings_municipality_status ON source_meetings(municipality_id, status);
CREATE INDEX IF NOT EXISTS idx_source_meetings_date ON source_meetings(meeting_date DESC);
CREATE INDEX IF NOT EXISTS idx_source_meetings_ingested ON source_meetings(ingested_meeting_id);

CREATE TABLE IF NOT EXISTS pipeline_jobs (
    id bigint generated by default as identity primary key,
    municipality_id bigint REFERENCES municipalities(id) ON DELETE CASCADE NOT NULL,
    job_type text NOT NULL,
    status text NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    args jsonb NOT NULL DEFAULT '{}'::jsonb,
    priority integer NOT NULL DEFAULT 0,
    requested_by text,
    requested_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    started_at timestamptz,
    finished_at timestamptz,
    locked_by text,
    locked_at timestamptz,
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 1,
    last_error text,
    result jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

DROP TRIGGER IF EXISTS set_timestamp_pipeline_jobs ON pipeline_jobs;
CREATE TRIGGER set_timestamp_pipeline_jobs
    BEFORE UPDATE ON pipeline_jobs
    FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_status_priority ON pipeline_jobs(status, priority DESC, requested_at);
CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_municipality_status ON pipeline_jobs(municipality_id, status);

CREATE TABLE IF NOT EXISTS pipeline_run_events (
    id bigint generated by default as identity primary key,
    job_id bigint REFERENCES pipeline_jobs(id) ON DELETE CASCADE NOT NULL,
    level text NOT NULL DEFAULT 'info'
        CHECK (level IN ('debug', 'info', 'warning', 'error')),
    message text NOT NULL,
    data jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pipeline_run_events_job_created ON pipeline_run_events(job_id, created_at);

CREATE OR REPLACE FUNCTION claim_next_pipeline_job(worker_id text)
RETURNS SETOF pipeline_jobs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN QUERY
    WITH next_job AS (
        SELECT id
        FROM pipeline_jobs
        WHERE status = 'queued'
          AND attempt_count < max_attempts
        ORDER BY priority DESC, requested_at ASC
        FOR UPDATE SKIP LOCKED
        LIMIT 1
    )
    UPDATE pipeline_jobs
    SET status = 'running',
        locked_by = worker_id,
        locked_at = timezone('utc'::text, now()),
        started_at = COALESCE(started_at, timezone('utc'::text, now())),
        attempt_count = attempt_count + 1,
        last_error = NULL
    WHERE id IN (SELECT id FROM next_job)
    RETURNING pipeline_jobs.*;
END;
$$;

ALTER TABLE source_meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_run_events ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Enable service role access on source_meetings"
        ON source_meetings FOR ALL
        USING (auth.role() = 'service_role')
        WITH CHECK (auth.role() = 'service_role');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE POLICY "Enable service role access on pipeline_jobs"
        ON pipeline_jobs FOR ALL
        USING (auth.role() = 'service_role')
        WITH CHECK (auth.role() = 'service_role');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE POLICY "Enable service role access on pipeline_run_events"
        ON pipeline_run_events FOR ALL
        USING (auth.role() = 'service_role')
        WITH CHECK (auth.role() = 'service_role');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
