-- Auth profile and subscription tables used by the web app.
-- The upstream bootstrap omitted these tables, which causes authenticated
-- requests to fail when the root loader checks onboarding/profile state.

DO $$ BEGIN
    CREATE TYPE subscription_type AS ENUM (
        'matter',
        'topic',
        'person',
        'neighborhood',
        'digest'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE digest_frequency AS ENUM (
        'each_meeting',
        'weekly'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS user_profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    display_name text,
    address text,
    neighborhood text,
    notification_email text,
    email_verified boolean not null default false,
    digest_frequency digest_frequency not null default 'each_meeting',
    digest_enabled boolean not null default false,
    onboarding_completed boolean not null default false,
    location_lat double precision,
    location_lng double precision,
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

DROP TRIGGER IF EXISTS set_timestamp_user_profiles ON user_profiles;
CREATE TRIGGER set_timestamp_user_profiles
BEFORE UPDATE ON user_profiles
FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE IF NOT EXISTS subscriptions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    type subscription_type not null,
    matter_id bigint references matters(id) on delete cascade,
    topic_id bigint references topics(id) on delete cascade,
    person_id bigint references people(id) on delete cascade,
    neighborhood text,
    proximity_radius_m integer not null default 1000,
    keyword text,
    keyword_embedding halfvec(384),
    is_active boolean not null default true,
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

DO $$ BEGIN
    ALTER TABLE subscriptions
    ADD CONSTRAINT subscriptions_unique_target UNIQUE (
        user_id,
        type,
        matter_id,
        topic_id,
        person_id,
        neighborhood,
        keyword
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DROP TRIGGER IF EXISTS set_timestamp_subscriptions ON subscriptions;
CREATE TRIGGER set_timestamp_subscriptions
BEFORE UPDATE ON subscriptions
FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_active_type ON subscriptions(type, is_active);
CREATE INDEX IF NOT EXISTS idx_subscriptions_keyword_embedding
  ON subscriptions USING hnsw (keyword_embedding halfvec_cosine_ops);

ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
    CREATE POLICY "Users can read their own profile" ON user_profiles
        FOR SELECT TO authenticated USING (auth.uid() = id);
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE POLICY "Users can insert their own profile" ON user_profiles
        FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE POLICY "Users can update their own profile" ON user_profiles
        FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE POLICY "Service role can manage user profiles" ON user_profiles
        FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE POLICY "Users can read their own subscriptions" ON subscriptions
        FOR SELECT TO authenticated USING (auth.uid() = user_id);
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE POLICY "Users can insert their own subscriptions" ON subscriptions
        FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE POLICY "Users can update their own subscriptions" ON subscriptions
        FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE POLICY "Users can delete their own subscriptions" ON subscriptions
        FOR DELETE TO authenticated USING (auth.uid() = user_id);
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE POLICY "Service role can manage subscriptions" ON subscriptions
        FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Backfill dashboard-created Auth users so profile lookups have a row.
INSERT INTO user_profiles (
    id,
    display_name,
    notification_email,
    email_verified,
    onboarding_completed
)
SELECT
    au.id,
    au.raw_user_meta_data->>'display_name',
    au.email,
    au.email_confirmed_at IS NOT NULL,
    false
FROM auth.users au
ON CONFLICT (id) DO NOTHING;

CREATE OR REPLACE FUNCTION update_user_location(
  target_user_id uuid,
  lng double precision,
  lat double precision
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = 'public'
AS $$
  UPDATE user_profiles
  SET location_lng = lng,
      location_lat = lat
  WHERE id = target_user_id;
$$;
