-- View Royal Council Intelligence Platform - Consolidated Schema Bootstrap
-- Includes Core Relational Schema + Intelligence Layer (V2)

-- Enable pgvector for semantic search
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 0. TYPES & ENUMS
DO $$ BEGIN
    CREATE TYPE meeting_type AS ENUM (
        'Regular Council',
        'Special Council',
        'Committee of the Whole',
        'Public Hearing',
        'Board of Variance',
        'Standing Committee',
        'Advisory Committee'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE org_classification AS ENUM (
        'Council',
        'Committee',
        'Board',
        'Advisory Committee',
        'Staff',
        'Other'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE subscription_type AS ENUM (
        'matter',
        'topic',
        'person',
        'neighborhood',
        'digest'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE digest_frequency AS ENUM (
        'each_meeting',
        'weekly'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 0.1 TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- 0.2 MUNICIPALITIES
CREATE TABLE IF NOT EXISTS municipalities (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name text not null,
    short_name text not null,
    province text default 'BC',
    classification text default 'City',
    source_config jsonb not null default '{}'::jsonb,
    map_center_lat float,
    map_center_lng float,
    website_url text,
    rss_url text,
    contact_email text,
    ocd_id text unique,
    meta jsonb,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

DROP TRIGGER IF EXISTS set_timestamp_municipalities ON municipalities;
CREATE TRIGGER set_timestamp_municipalities BEFORE UPDATE ON municipalities FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

INSERT INTO municipalities (
    id, slug, name, short_name, province, classification, source_config,
    map_center_lat, map_center_lng, website_url, rss_url, contact_email, meta
) VALUES (
    1,
    'langford',
    'City of Langford',
    'Langford',
    'BC',
    'City',
    '{
        "type": "escribe",
        "base_url": "https://pub-langford.escribemeetings.com",
        "verify_ssl": false,
        "meeting_types": [
            "Council Meeting",
            "Special Council Meeting",
            "Committee of the Whole Meeting",
            "Public Hearing",
            "Community Advisory Committee"
        ],
        "video_source": {
            "type": "isilive",
            "client_id": "langford"
        }
    }'::jsonb,
    48.4496,
    -123.5047,
    'https://langford.ca',
    NULL,
    NULL,
    '{}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    short_name = EXCLUDED.short_name,
    province = EXCLUDED.province,
    classification = EXCLUDED.classification,
    source_config = EXCLUDED.source_config,
    map_center_lat = EXCLUDED.map_center_lat,
    map_center_lng = EXCLUDED.map_center_lng,
    website_url = EXCLUDED.website_url,
    rss_url = EXCLUDED.rss_url,
    contact_email = EXCLUDED.contact_email,
    meta = EXCLUDED.meta;

-- 1. ORGANIZATIONS
CREATE TABLE IF NOT EXISTS organizations (
    id bigint generated by default as identity primary key,
    name text not null unique,
    classification org_classification default 'Committee',
    municipality_id bigint REFERENCES municipalities(id) DEFAULT 1,
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS idx_organizations_municipality_id ON organizations(municipality_id);

DROP TRIGGER IF EXISTS set_timestamp_organizations ON organizations;
CREATE TRIGGER set_timestamp_organizations BEFORE UPDATE ON organizations FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 2. PEOPLE
CREATE TABLE IF NOT EXISTS people (
    id bigint generated by default as identity primary key,
    name text not null unique,
    is_councillor boolean default false,
    email text,
    image_url text,
    bio text,
    voice_fingerprint_id text,
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

DROP TRIGGER IF EXISTS set_timestamp_people ON people;
CREATE TRIGGER set_timestamp_people BEFORE UPDATE ON people FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 3. MEMBERSHIPS
CREATE TABLE IF NOT EXISTS memberships (
    id bigint generated by default as identity primary key,
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    organization_id bigint REFERENCES organizations(id) ON DELETE CASCADE not null,
    role text, -- "Chair", "Vice-Chair", "Member"
    start_date date,
    end_date date,
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

DROP TRIGGER IF EXISTS set_timestamp_memberships ON memberships;
CREATE TRIGGER set_timestamp_memberships BEFORE UPDATE ON memberships FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- Seed active Langford council roster. This governance data is not reliably
-- derivable from meeting transcripts and should exist before ingestion.
INSERT INTO organizations (name, classification, municipality_id)
VALUES ('Council', 'Council', 1)
ON CONFLICT (name) DO UPDATE SET
    classification = EXCLUDED.classification,
    municipality_id = EXCLUDED.municipality_id;

INSERT INTO people (name, is_councillor)
VALUES
    ('S. Goodmanson', true),
    ('K. Guiry', true),
    ('C. Harder', true),
    ('M. Morley', true),
    ('M. Wagner', true),
    ('K. Yacucha', true),
    ('L. Szpak', true)
ON CONFLICT (name) DO UPDATE SET
    is_councillor = EXCLUDED.is_councillor;

INSERT INTO memberships (person_id, organization_id, role, start_date, end_date)
SELECT p.id, o.id, roster.role, DATE '2022-11-01', roster.end_date::date
FROM (
    VALUES
        ('S. Goodmanson', 'Mayor', NULL),
        ('K. Guiry', 'Councillor', NULL),
        ('C. Harder', 'Councillor', NULL),
        ('M. Morley', 'Councillor', NULL),
        ('M. Wagner', 'Councillor', NULL),
        ('K. Yacucha', 'Councillor', NULL),
        ('L. Szpak', 'Councillor', '2026-05-02')
) AS roster(name, role, end_date)
JOIN people p ON p.name = roster.name
JOIN organizations o ON o.name = 'Council' AND o.municipality_id = 1
WHERE NOT EXISTS (
    SELECT 1
    FROM memberships m
    WHERE m.person_id = p.id
      AND m.organization_id = o.id
      AND m.role = roster.role
);

INSERT INTO organizations (name, classification, municipality_id)
VALUES
    ('RCMP', 'Staff', 1),
    ('BC Economic Development Association', 'Staff', 1),
    ('Community Advisory Committee', 'Committee', 1),
    ('Sustainable Development Advisory Committee', 'Committee', 1)
ON CONFLICT (name) DO UPDATE SET
    classification = EXCLUDED.classification,
    municipality_id = EXCLUDED.municipality_id;

INSERT INTO people (name, is_councillor)
VALUES
    ('Supt. T. Gillespie', false),
    ('Dale Wheeldon', false),
    ('Colleen Bond', false),
    ('Jacqui Whiteway', false),
    ('Chris Foxall', false),
    ('Moira McDonald', false),
    ('Robin Plomp', false),
    ('Frazer Johnson', false),
    ('Nicolas Lehman', false),
    ('Malcolm McNaughton', false),
    ('Brandy Gordon', false),
    ('Sarah Cotter', false),
    ('Bill Benbow', false),
    ('Vasile Dumitru', false),
    ('Matthew Rodgers', false)
ON CONFLICT (name) DO NOTHING;

INSERT INTO memberships (person_id, organization_id, role, start_date, end_date)
SELECT p.id, o.id, roster.role, DATE '2022-11-01', roster.end_date::date
FROM (
    VALUES
        ('Supt. T. Gillespie', 'RCMP', 'Superintendent', NULL),
        ('Dale Wheeldon', 'BC Economic Development Association', 'President and CEO', NULL),
        ('Colleen Bond', 'BC Economic Development Association', 'Representative', NULL),
        ('K. Yacucha', 'Community Advisory Committee', 'Council Representative', NULL),
        ('C. Harder', 'Community Advisory Committee', 'Council Representative', NULL),
        ('M. Morley', 'Community Advisory Committee', 'Council Representative', NULL),
        ('Jacqui Whiteway', 'Community Advisory Committee', 'Citizen Representative', NULL),
        ('Chris Foxall', 'Community Advisory Committee', 'Citizen Representative', NULL),
        ('Moira McDonald', 'Community Advisory Committee', 'Citizen Representative', NULL),
        ('Robin Plomp', 'Community Advisory Committee', 'Citizen Representative', NULL),
        ('Frazer Johnson', 'Community Advisory Committee', 'Citizen Representative', NULL),
        ('Nicolas Lehman', 'Community Advisory Committee', 'Citizen Representative', NULL),
        ('L. Szpak', 'Sustainable Development Advisory Committee', 'Council Representative', '2026-05-02'),
        ('M. Wagner', 'Sustainable Development Advisory Committee', 'Council Representative', NULL),
        ('K. Guiry', 'Sustainable Development Advisory Committee', 'Council Representative', NULL),
        ('Malcolm McNaughton', 'Sustainable Development Advisory Committee', 'Citizen Representative', NULL),
        ('Brandy Gordon', 'Sustainable Development Advisory Committee', 'Citizen Representative', NULL),
        ('Sarah Cotter', 'Sustainable Development Advisory Committee', 'Citizen Representative', NULL),
        ('Bill Benbow', 'Sustainable Development Advisory Committee', 'Citizen Representative', NULL),
        ('Vasile Dumitru', 'Sustainable Development Advisory Committee', 'Citizen Representative', NULL),
        ('Matthew Rodgers', 'Sustainable Development Advisory Committee', 'Citizen Representative', NULL)
) AS roster(name, org_name, role, end_date)
JOIN people p ON p.name = roster.name
JOIN organizations o ON o.name = roster.org_name AND o.municipality_id = 1
WHERE NOT EXISTS (
    SELECT 1
    FROM memberships m
    WHERE m.person_id = p.id
      AND m.organization_id = o.id
      AND m.role = roster.role
);

-- 4. ELECTIONS: Governance History
CREATE TABLE IF NOT EXISTS elections (
    id bigint generated by default as identity primary key,
    name text not null unique, -- "2022 General Local Election"
    election_date date not null,
    classification text, -- "General", "By-election"
    term_length_years int,
    notes text,
    source_id int, -- CivicInfo ID
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

DROP TRIGGER IF EXISTS set_timestamp_elections ON elections;
CREATE TRIGGER set_timestamp_elections BEFORE UPDATE ON elections FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE IF NOT EXISTS election_offices (
    id bigint generated by default as identity primary key,
    election_id bigint REFERENCES elections(id) ON DELETE CASCADE not null,
    office text not null, -- "Mayor", "Councillor"
    seats_available int,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(election_id, office)
);

DROP TRIGGER IF EXISTS set_timestamp_election_offices ON election_offices;
CREATE TRIGGER set_timestamp_election_offices BEFORE UPDATE ON election_offices FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE IF NOT EXISTS candidacies (
    id bigint generated by default as identity primary key,
    election_office_id bigint REFERENCES election_offices(id) ON DELETE CASCADE not null,
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    is_elected boolean default false,
    is_acclaimed boolean default false,
    votes_received int,
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(election_office_id, person_id)
);

DROP TRIGGER IF EXISTS set_timestamp_candidacies ON candidacies;
CREATE TRIGGER set_timestamp_candidacies BEFORE UPDATE ON candidacies FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 5. MEETINGS
CREATE TABLE IF NOT EXISTS meetings (
    id bigint generated by default as identity primary key,
    organization_id bigint REFERENCES organizations(id) ON DELETE SET NULL,
    municipality_id bigint REFERENCES municipalities(id) DEFAULT 1,
    title text not null,
    meeting_date date not null,
    type meeting_type,
    status text default 'Planned', -- 'Planned', 'Completed', 'Cancelled'

    -- Ingestion Status Flags
    has_agenda boolean default false,
    has_minutes boolean default false,
    has_transcript boolean default false,

    video_url text,
    minutes_url text,
    agenda_url text,
    video_duration_seconds int,
    chair_person_id bigint REFERENCES people(id) ON DELETE SET NULL,
    archive_path text unique,
    summary text,
    embedding halfvec(384),
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS idx_meetings_municipality_id ON meetings(municipality_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_meetings_muni_date_type ON meetings(municipality_id, meeting_date, type);

DROP TRIGGER IF EXISTS set_timestamp_meetings ON meetings;
CREATE TRIGGER set_timestamp_meetings BEFORE UPDATE ON meetings FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 6. ATTENDANCE
CREATE TABLE IF NOT EXISTS attendance (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE not null,
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    attendance_mode text check (attendance_mode in ('In Person', 'Remote', 'Absent', 'Regrets', 'Unknown')) default 'Unknown',
    arrival_time timestamp with time zone,
    departure_time timestamp with time zone,
    notes text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(meeting_id, person_id)
);

DROP TRIGGER IF EXISTS set_timestamp_attendance ON attendance;
CREATE TRIGGER set_timestamp_attendance BEFORE UPDATE ON attendance FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 7. MATTERS (Longitudinal topics/bylaws)
CREATE TABLE IF NOT EXISTS matters (
    id bigint generated by default as identity primary key,
    title text not null,
    identifier text unique, -- "Bylaw 1540"
    municipality_id bigint REFERENCES municipalities(id) DEFAULT 1,
    description text,
    plain_english_summary text,
    category text,
    status text default 'Active',
    first_seen date,
    last_seen date,
    geo_location jsonb,
    embedding halfvec(384),
    text_search tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(plain_english_summary, description, ''))) STORED,
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS idx_matters_municipality_id ON matters(municipality_id);

DROP TRIGGER IF EXISTS set_timestamp_matters ON matters;
CREATE TRIGGER set_timestamp_matters BEFORE UPDATE ON matters FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 8. AGENDA ITEMS
CREATE TABLE IF NOT EXISTS agenda_items (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE not null,
    matter_id bigint REFERENCES matters(id) ON DELETE SET NULL,
    parent_id bigint REFERENCES agenda_items(id) ON DELETE CASCADE,

    item_order text,
    title text not null,
    description text,
    plain_english_summary text,
    category text,

    is_consent_agenda boolean default false,
    matter_status_snapshot text,
    related_address text,
    geo_location jsonb,
    neighborhood text,
    debate_summary text,
    is_controversial boolean default false,

    discussion_start_time float,
    discussion_end_time float,
    financial_cost numeric,
    funding_source text,
    keywords text[],

    source_file text,
    embedding halfvec(384),
    text_search tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(plain_english_summary, '') || ' ' || coalesce(debate_summary, ''))) STORED,
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

DROP TRIGGER IF EXISTS set_timestamp_agenda_items ON agenda_items;
CREATE TRIGGER set_timestamp_agenda_items BEFORE UPDATE ON agenda_items FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE INDEX IF NOT EXISTS idx_agenda_neighborhood ON agenda_items(neighborhood);

-- 9. TOPICS (Controlled taxonomy)
CREATE TABLE IF NOT EXISTS topics (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

DROP TRIGGER IF EXISTS set_timestamp_topics ON topics;
CREATE TRIGGER set_timestamp_topics BEFORE UPDATE ON topics FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE IF NOT EXISTS agenda_item_topics (
    agenda_item_id bigint REFERENCES agenda_items(id) ON DELETE CASCADE,
    topic_id bigint REFERENCES topics(id) ON DELETE CASCADE,
    PRIMARY KEY (agenda_item_id, topic_id)
);

-- 9b. USER PROFILES & SUBSCRIPTIONS
CREATE TABLE IF NOT EXISTS user_profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    display_name text,
    address text,
    neighborhood text,
    notification_email text,
    email_verified boolean not null default false,
    digest_frequency digest_frequency not null default 'each_meeting',
    digest_enabled boolean not null default false,
    onboarding_completed boolean not null default false,
    location_lat double precision,
    location_lng double precision,
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

DROP TRIGGER IF EXISTS set_timestamp_user_profiles ON user_profiles;
CREATE TRIGGER set_timestamp_user_profiles BEFORE UPDATE ON user_profiles FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE IF NOT EXISTS subscriptions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    type subscription_type not null,
    matter_id bigint references matters(id) on delete cascade,
    topic_id bigint references topics(id) on delete cascade,
    person_id bigint references people(id) on delete cascade,
    neighborhood text,
    proximity_radius_m integer not null default 1000,
    keyword text,
    keyword_embedding halfvec(384),
    is_active boolean not null default true,
    meta jsonb not null default '{}'::jsonb,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

DO $$ BEGIN
    ALTER TABLE subscriptions
    ADD CONSTRAINT subscriptions_unique_target UNIQUE (
        user_id,
        type,
        matter_id,
        topic_id,
        person_id,
        neighborhood,
        keyword
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DROP TRIGGER IF EXISTS set_timestamp_subscriptions ON subscriptions;
CREATE TRIGGER set_timestamp_subscriptions BEFORE UPDATE ON subscriptions FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 10. MOTIONS
CREATE TABLE IF NOT EXISTS motions (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE not null,
    agenda_item_id bigint REFERENCES agenda_items(id) ON DELETE CASCADE not null,

    mover text,
    seconder text,
    mover_id bigint REFERENCES people(id) ON DELETE SET NULL,
    seconder_id bigint REFERENCES people(id) ON DELETE SET NULL,
    text_content text not null,
    plain_english_summary text,

    disposition text, -- "Substantive", "Procedural", "Tabled", "Referred"
    result text, -- "CARRIED", "DEFEATED", "WITHDRAWN"

    yes_votes int DEFAULT 0,
    no_votes int DEFAULT 0,
    abstain_votes int DEFAULT 0,
    absent_votes int DEFAULT 0,

    time_offset_seconds float,
    financial_cost numeric,
    funding_source text,

    embedding halfvec(384),
    text_search tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(plain_english_summary, text_content, ''))) STORED,
    meta jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

DROP TRIGGER IF EXISTS set_timestamp_motions ON motions;
CREATE TRIGGER set_timestamp_motions BEFORE UPDATE ON motions FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 11. VOTES
CREATE TABLE IF NOT EXISTS votes (
    id bigint generated by default as identity primary key,
    motion_id bigint REFERENCES motions(id) ON DELETE CASCADE not null,
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    vote text not null, -- "Yes", "No", "Abstain", "Recused"
    recusal_reason text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(motion_id, person_id)
);

DROP TRIGGER IF EXISTS set_timestamp_votes ON votes;
CREATE TRIGGER set_timestamp_votes BEFORE UPDATE ON votes FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 12. TRANSCRIPT SEGMENTS
CREATE TABLE IF NOT EXISTS transcript_segments (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE not null,
    person_id bigint REFERENCES people(id) ON DELETE SET NULL,
    agenda_item_id bigint REFERENCES agenda_items(id) ON DELETE SET NULL,
    motion_id bigint REFERENCES motions(id) ON DELETE SET NULL,

    speaker_name text,
    speaker_role text,

    start_time float not null,
    end_time float not null,
    text_content text not null,

    attribution_source text default 'AI_DIARIZATION',
    is_verified boolean default false,
    is_procedural boolean default false,
    sentiment_score float,
    text_search tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(text_content, ''))) STORED,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

DROP TRIGGER IF EXISTS set_timestamp_transcript_segments ON transcript_segments;
CREATE TRIGGER set_timestamp_transcript_segments BEFORE UPDATE ON transcript_segments FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 13. SPEAKER ALIASES
CREATE TABLE IF NOT EXISTS meeting_speaker_aliases (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE not null,
    speaker_label text not null,
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(meeting_id, speaker_label)
);

DROP TRIGGER IF EXISTS set_timestamp_meeting_speaker_aliases ON meeting_speaker_aliases;
CREATE TRIGGER set_timestamp_meeting_speaker_aliases BEFORE UPDATE ON meeting_speaker_aliases FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 14. VOICE FINGERPRINTS
CREATE TABLE IF NOT EXISTS voice_fingerprints (
    id uuid primary key default gen_random_uuid(),
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    embedding jsonb not null,
    source_meeting_id bigint REFERENCES meetings(id) ON DELETE SET NULL,
    confidence float default 1.0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(person_id)
);

CREATE INDEX IF NOT EXISTS idx_voice_fingerprints_person_id ON voice_fingerprints(person_id);
CREATE INDEX IF NOT EXISTS idx_voice_fingerprints_source_meeting_id ON voice_fingerprints(source_meeting_id);

DROP TRIGGER IF EXISTS set_timestamp_voice_fingerprints ON voice_fingerprints;
CREATE TRIGGER set_timestamp_voice_fingerprints BEFORE UPDATE ON voice_fingerprints FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 15. MEETING EVENTS
CREATE TABLE IF NOT EXISTS meeting_events (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE not null,
    person_id bigint REFERENCES people(id) ON DELETE CASCADE not null,
    event_type text not null, -- 'Left Meeting', 'Returned', 'Recused'
    time_offset_seconds int,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

DROP TRIGGER IF EXISTS set_timestamp_meeting_events ON meeting_events;
CREATE TRIGGER set_timestamp_meeting_events BEFORE UPDATE ON meeting_events FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

-- 15. BYLAWS (Reference Documents)
CREATE TABLE IF NOT EXISTS bylaws (
    id bigint generated by default as identity primary key,
    title text not null,
    bylaw_number text,
    municipality_id bigint REFERENCES municipalities(id) DEFAULT 1,
    year int,
    category text,
    status text default 'Active',
    file_path text unique,
    source_url text,
    full_text text,
    plain_english_summary text,
    embedding halfvec(384),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS idx_bylaws_municipality_id ON bylaws(municipality_id);

DROP TRIGGER IF EXISTS set_timestamp_bylaws ON bylaws;
CREATE TRIGGER set_timestamp_bylaws BEFORE UPDATE ON bylaws FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE TABLE IF NOT EXISTS bylaw_chunks (
    id bigint generated by default as identity primary key,
    bylaw_id bigint REFERENCES bylaws(id) ON DELETE CASCADE not null,
    chunk_index int not null,
    text_content text not null,
    embedding halfvec(384),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS idx_bylaws_title ON bylaws(title);
CREATE INDEX IF NOT EXISTS idx_bylaws_number ON bylaws(bylaw_number);
CREATE INDEX IF NOT EXISTS idx_bylaw_chunks_bylaw_id ON bylaw_chunks(bylaw_id);

ALTER TABLE matters ADD COLUMN IF NOT EXISTS bylaw_id bigint;
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'matters_bylaw_id_fkey'
    ) THEN
        ALTER TABLE matters
            ADD CONSTRAINT matters_bylaw_id_fkey
            FOREIGN KEY (bylaw_id) REFERENCES bylaws(id) ON DELETE SET NULL;
    END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_matters_bylaw_id ON matters(bylaw_id);

-- 16. DOCUMENTS (Meeting PDFs)
CREATE TABLE IF NOT EXISTS documents (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE NOT NULL,
    title text NOT NULL,
    category text NOT NULL DEFAULT 'Other',
    source_url text,
    file_path text NOT NULL,
    file_hash text,
    full_text text,
    page_count integer,
    embedding halfvec(384),
    municipality_id bigint REFERENCES municipalities(id) DEFAULT 1,
    created_at timestamptz default timezone('utc'::text, now()) not null,
    updated_at timestamptz default timezone('utc'::text, now()) not null,
    UNIQUE(meeting_id, file_path)
);

CREATE TRIGGER set_timestamp_documents
    BEFORE UPDATE ON documents
    FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE INDEX IF NOT EXISTS idx_documents_meeting_id ON documents(meeting_id);
CREATE INDEX IF NOT EXISTS idx_documents_category ON documents(category);
CREATE INDEX IF NOT EXISTS idx_documents_municipality_id ON documents(municipality_id);

-- 16b. KEY STATEMENTS (Extracted typed statements from discussions)
CREATE TABLE IF NOT EXISTS key_statements (
    id bigint generated by default as identity primary key,
    meeting_id bigint REFERENCES meetings(id) ON DELETE CASCADE NOT NULL,
    agenda_item_id bigint REFERENCES agenda_items(id) ON DELETE SET NULL,
    speaker_name text,
    person_id bigint REFERENCES people(id) ON DELETE SET NULL,
    statement_type text NOT NULL,  -- claim, proposal, objection, recommendation, financial, public_input
    statement_text text NOT NULL,
    context text,
    source_segment_ids bigint[],
    start_time float,
    municipality_id bigint REFERENCES municipalities(id) DEFAULT 1,
    embedding halfvec(384),
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TRIGGER set_timestamp_key_statements
    BEFORE UPDATE ON key_statements
    FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE INDEX IF NOT EXISTS idx_key_statements_meeting_id ON key_statements(meeting_id);
CREATE INDEX IF NOT EXISTS idx_key_statements_agenda_item_id ON key_statements(agenda_item_id);
CREATE INDEX IF NOT EXISTS idx_key_statements_municipality_id ON key_statements(municipality_id);
CREATE INDEX IF NOT EXISTS idx_key_statements_type ON key_statements(statement_type);
CREATE INDEX IF NOT EXISTS idx_key_statements_person_id ON key_statements(person_id);

-- 17. EXTRACTED DOCUMENTS & SECTIONS
CREATE TABLE IF NOT EXISTS extracted_documents (
    id bigint generated by default as identity primary key,
    document_id bigint REFERENCES documents(id) ON DELETE CASCADE NOT NULL,
    agenda_item_id bigint REFERENCES agenda_items(id) ON DELETE SET NULL,
    title text NOT NULL,
    document_type text NOT NULL DEFAULT 'other',
    page_start integer,
    page_end integer,
    summary text,
    key_facts jsonb,
    municipality_id bigint REFERENCES municipalities(id) DEFAULT 1,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_extracted_documents_document ON extracted_documents(document_id);
CREATE INDEX IF NOT EXISTS idx_extracted_documents_agenda_item ON extracted_documents(agenda_item_id);
CREATE INDEX IF NOT EXISTS idx_extracted_documents_type ON extracted_documents(document_type);

CREATE TABLE IF NOT EXISTS document_sections (
    id bigint generated by default as identity primary key,
    document_id bigint REFERENCES documents(id) ON DELETE CASCADE NOT NULL,
    extracted_document_id bigint REFERENCES extracted_documents(id) ON DELETE CASCADE,
    agenda_item_id bigint REFERENCES agenda_items(id) ON DELETE SET NULL,
    section_title text,
    section_text text NOT NULL,
    section_order integer NOT NULL,
    page_start integer,
    page_end integer,
    token_count integer,
    embedding halfvec(384),
    text_search tsvector GENERATED ALWAYS AS (
        to_tsvector('english', coalesce(section_title, '') || ' ' || coalesce(section_text, ''))
    ) STORED,
    municipality_id bigint REFERENCES municipalities(id) DEFAULT 1,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_document_sections_document ON document_sections(document_id);
CREATE INDEX IF NOT EXISTS idx_document_sections_extracted_doc ON document_sections(extracted_document_id);
CREATE INDEX IF NOT EXISTS idx_document_sections_agenda_item ON document_sections(agenda_item_id);
CREATE INDEX IF NOT EXISTS idx_document_sections_municipality_id ON document_sections(municipality_id);
CREATE INDEX IF NOT EXISTS idx_document_sections_search ON document_sections USING gin(text_search);

CREATE TABLE IF NOT EXISTS document_images (
    id bigint generated by default as identity primary key,
    extracted_document_id bigint REFERENCES extracted_documents(id) ON DELETE CASCADE NOT NULL,
    document_section_id bigint REFERENCES document_sections(id) ON DELETE SET NULL,
    r2_key text NOT NULL,
    page integer NOT NULL,
    description text,
    image_type text DEFAULT 'other',
    width integer,
    height integer,
    format text,
    file_size integer,
    municipality_id bigint REFERENCES municipalities(id) DEFAULT 1,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_document_images_extracted_doc ON document_images(extracted_document_id);
CREATE INDEX IF NOT EXISTS idx_document_images_section ON document_images(document_section_id);
CREATE INDEX IF NOT EXISTS idx_document_images_municipality_id ON document_images(municipality_id);

-- 17b. PIPELINE OPS CONSOLE
CREATE TABLE IF NOT EXISTS source_meetings (
    id bigint generated by default as identity primary key,
    municipality_id bigint REFERENCES municipalities(id) ON DELETE CASCADE NOT NULL,
    source_type text NOT NULL,
    source_id text NOT NULL,
    meeting_date date NOT NULL,
    title text NOT NULL,
    meeting_type text,
    source_url text,
    video_url text,
    archive_path text,
    raw jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'discovered',
    last_error text,
    discovered_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    last_seen_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    ingested_meeting_id bigint REFERENCES meetings(id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE (municipality_id, source_type, source_id)
);

DROP TRIGGER IF EXISTS set_timestamp_source_meetings ON source_meetings;
CREATE TRIGGER set_timestamp_source_meetings
    BEFORE UPDATE ON source_meetings
    FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE INDEX IF NOT EXISTS idx_source_meetings_municipality_status ON source_meetings(municipality_id, status);
CREATE INDEX IF NOT EXISTS idx_source_meetings_date ON source_meetings(meeting_date DESC);
CREATE INDEX IF NOT EXISTS idx_source_meetings_ingested ON source_meetings(ingested_meeting_id);

CREATE TABLE IF NOT EXISTS pipeline_jobs (
    id bigint generated by default as identity primary key,
    municipality_id bigint REFERENCES municipalities(id) ON DELETE CASCADE NOT NULL,
    job_type text NOT NULL,
    status text NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    args jsonb NOT NULL DEFAULT '{}'::jsonb,
    priority integer NOT NULL DEFAULT 0,
    requested_by text,
    requested_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    started_at timestamptz,
    finished_at timestamptz,
    locked_by text,
    locked_at timestamptz,
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 1,
    last_error text,
    result jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

DROP TRIGGER IF EXISTS set_timestamp_pipeline_jobs ON pipeline_jobs;
CREATE TRIGGER set_timestamp_pipeline_jobs
    BEFORE UPDATE ON pipeline_jobs
    FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_status_priority ON pipeline_jobs(status, priority DESC, requested_at);
CREATE INDEX IF NOT EXISTS idx_pipeline_jobs_municipality_status ON pipeline_jobs(municipality_id, status);

CREATE TABLE IF NOT EXISTS pipeline_run_events (
    id bigint generated by default as identity primary key,
    job_id bigint REFERENCES pipeline_jobs(id) ON DELETE CASCADE NOT NULL,
    level text NOT NULL DEFAULT 'info'
        CHECK (level IN ('debug', 'info', 'warning', 'error')),
    message text NOT NULL,
    data jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pipeline_run_events_job_created ON pipeline_run_events(job_id, created_at);

CREATE OR REPLACE FUNCTION claim_next_pipeline_job(
    worker_id text,
    job_types text[] DEFAULT NULL
)
RETURNS SETOF pipeline_jobs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN QUERY
    WITH next_job AS (
        SELECT pj.id
        FROM pipeline_jobs pj
        WHERE pj.status = 'queued'
          AND pj.attempt_count < pj.max_attempts
          AND (job_types IS NULL OR pj.job_type = ANY(job_types))
          AND (
              NOT (pj.args ? 'source_meeting_id')
              OR pg_try_advisory_xact_lock(
                  pj.municipality_id::integer,
                  hashtext(pj.args->>'source_meeting_id')
              )
          )
          AND NOT EXISTS (
              SELECT 1
              FROM pipeline_jobs running
              WHERE running.status = 'running'
                AND running.id <> pj.id
                AND running.municipality_id = pj.municipality_id
                AND running.args ? 'source_meeting_id'
                AND pj.args ? 'source_meeting_id'
                AND running.args->>'source_meeting_id' = pj.args->>'source_meeting_id'
          )
        ORDER BY pj.priority DESC, pj.requested_at ASC
        FOR UPDATE SKIP LOCKED
        LIMIT 1
    )
    UPDATE pipeline_jobs
    SET status = 'running',
        locked_by = worker_id,
        locked_at = timezone('utc'::text, now()),
        started_at = COALESCE(started_at, timezone('utc'::text, now())),
        attempt_count = attempt_count + 1,
        last_error = NULL
    WHERE id IN (SELECT id FROM next_job)
    RETURNING pipeline_jobs.*;
END;
$$;

-- 17. SEMANTIC SEARCH INDEXES (HNSW)
-- We use cosine distance with halfvec(384) embeddings (text-embedding-3-small, Matryoshka truncation).
CREATE INDEX IF NOT EXISTS idx_motions_embedding ON motions USING hnsw (embedding halfvec_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_agenda_items_embedding ON agenda_items USING hnsw (embedding halfvec_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_matters_embedding ON matters USING hnsw (embedding halfvec_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_meetings_embedding ON meetings USING hnsw (embedding halfvec_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_bylaws_embedding ON bylaws USING hnsw (embedding halfvec_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_bylaw_chunks_embedding ON bylaw_chunks USING hnsw (embedding halfvec_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_documents_embedding ON documents USING hnsw (embedding halfvec_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_key_statements_embedding ON key_statements USING hnsw (embedding halfvec_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_subscriptions_keyword_embedding ON subscriptions USING hnsw (keyword_embedding halfvec_cosine_ops);

-- 17b. FULL-TEXT SEARCH INDEXES (GIN)
CREATE INDEX IF NOT EXISTS idx_ts_segments_fts ON transcript_segments USING GIN (text_search);
CREATE INDEX IF NOT EXISTS idx_motions_fts ON motions USING GIN (text_search);
CREATE INDEX IF NOT EXISTS idx_agenda_items_fts ON agenda_items USING GIN (text_search);
CREATE INDEX IF NOT EXISTS idx_matters_fts ON matters USING GIN (text_search);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_active_type ON subscriptions(type, is_active);

-- 18. ROW LEVEL SECURITY
ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE people ENABLE ROW LEVEL SECURITY;
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE elections ENABLE ROW LEVEL SECURITY;
ALTER TABLE election_offices ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidacies ENABLE ROW LEVEL SECURITY;
ALTER TABLE meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE matters ENABLE ROW LEVEL SECURITY;
ALTER TABLE agenda_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE agenda_item_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE motions ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE transcript_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE meeting_speaker_aliases ENABLE ROW LEVEL SECURITY;
ALTER TABLE voice_fingerprints ENABLE ROW LEVEL SECURITY;
ALTER TABLE meeting_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE bylaws ENABLE ROW LEVEL SECURITY;
ALTER TABLE bylaw_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE key_statements ENABLE ROW LEVEL SECURITY;
ALTER TABLE extracted_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE source_meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_run_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;

-- 19. PUBLIC READ POLICIES
CREATE POLICY "Allow public read-only access on organizations" ON organizations FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on people" ON people FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on memberships" ON memberships FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on elections" ON elections FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on election_offices" ON election_offices FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on candidacies" ON candidacies FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on meetings" ON meetings FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on attendance" ON attendance FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on matters" ON matters FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on agenda_items" ON agenda_items FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on topics" ON topics FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on agenda_item_topics" ON agenda_item_topics FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on motions" ON motions FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on votes" ON votes FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on transcript_segments" ON transcript_segments FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on meeting_speaker_aliases" ON meeting_speaker_aliases FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on voice_fingerprints" ON voice_fingerprints FOR SELECT TO public USING (true);
CREATE POLICY "Enable service role access on voice_fingerprints" ON voice_fingerprints FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Allow public read-only access on meeting_events" ON meeting_events FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on bylaws" ON bylaws FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on bylaw_chunks" ON bylaw_chunks FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read access on documents" ON documents FOR SELECT TO public USING (true);

CREATE POLICY "Enable write access for service role on bylaws" ON bylaws USING (auth.role() = 'service_role');
CREATE POLICY "Enable write access for service role on bylaw_chunks" ON bylaw_chunks USING (auth.role() = 'service_role');
CREATE POLICY "Enable write for service role on documents" ON documents FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Allow public read-only access on key_statements" ON key_statements FOR SELECT TO public USING (true);
CREATE POLICY "Enable write for service role on key_statements" ON key_statements FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Allow public read-only access on extracted_documents" ON extracted_documents FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on document_sections" ON document_sections FOR SELECT TO public USING (true);
CREATE POLICY "Allow public read-only access on document_images" ON document_images FOR SELECT TO public USING (true);

CREATE POLICY "Enable service role access on source_meetings" ON source_meetings FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Enable service role access on pipeline_jobs" ON pipeline_jobs FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Enable service role access on pipeline_run_events" ON pipeline_run_events FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Users can read their own profile" ON user_profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile" ON user_profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON user_profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Service role can manage user profiles" ON user_profiles FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Users can read their own subscriptions" ON subscriptions FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own subscriptions" ON subscriptions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own subscriptions" ON subscriptions FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own subscriptions" ON subscriptions FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Service role can manage subscriptions" ON subscriptions FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

-- 20. SEMANTIC SEARCH FUNCTIONS (RPC)

CREATE OR REPLACE FUNCTION update_user_location(
  target_user_id uuid,
  lng double precision,
  lat double precision
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = 'public'
AS $$
  UPDATE user_profiles
  SET location_lng = lng,
      location_lat = lat
  WHERE id = target_user_id;
$$;

CREATE OR REPLACE FUNCTION match_motions (
  query_embedding halfvec(384),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  meeting_id bigint,
  agenda_item_id bigint,
  text_content text,
  mover text,
  seconder text,
  result text,
  similarity float
)
LANGUAGE plpgsql
SET search_path = 'public'
AS $$
BEGIN
  RETURN QUERY
  SELECT
    m.id, m.meeting_id, m.agenda_item_id, m.text_content,
    m.mover, m.seconder, m.result,
    1 - (m.embedding <=> query_embedding) AS similarity
  FROM motions m
  WHERE 1 - (m.embedding <=> query_embedding) > match_threshold
  ORDER BY m.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

CREATE OR REPLACE FUNCTION match_matters (
  query_embedding halfvec(384),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  title text,
  plain_english_summary text,
  similarity float
)
LANGUAGE plpgsql
SET search_path = 'public'
AS $$
BEGIN
  RETURN QUERY
  SELECT
    ma.id, ma.title, ma.plain_english_summary,
    1 - (ma.embedding <=> query_embedding) AS similarity
  FROM matters ma
  WHERE 1 - (ma.embedding <=> query_embedding) > match_threshold
  ORDER BY ma.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

CREATE OR REPLACE FUNCTION match_agenda_items (
  query_embedding halfvec(384),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  meeting_id bigint,
  title text,
  plain_english_summary text,
  debate_summary text,
  similarity float
)
LANGUAGE plpgsql
SET search_path = 'public'
AS $$
BEGIN
  RETURN QUERY
  SELECT
    ai.id, ai.meeting_id, ai.title, ai.plain_english_summary, ai.debate_summary,
    1 - (ai.embedding <=> query_embedding) AS similarity
  FROM agenda_items ai
  WHERE 1 - (ai.embedding <=> query_embedding) > match_threshold
  ORDER BY ai.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

CREATE OR REPLACE FUNCTION match_bylaws (
  query_embedding halfvec(384),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  title text,
  bylaw_number text,
  plain_english_summary text,
  similarity float
)
LANGUAGE plpgsql
SET search_path = 'public'
AS $$
BEGIN
  RETURN QUERY
  SELECT
    b.id,
    b.title,
    b.bylaw_number,
    b.plain_english_summary,
    1 - (b.embedding <=> query_embedding) AS similarity
  FROM bylaws b
  WHERE 1 - (b.embedding <=> query_embedding) > match_threshold
  ORDER BY b.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

CREATE OR REPLACE FUNCTION match_bylaw_chunks (
  query_embedding halfvec(384),
  match_threshold float,
  match_count int,
  filter_bylaw_id bigint DEFAULT NULL
)
RETURNS TABLE (
  id bigint,
  bylaw_id bigint,
  chunk_index int,
  text_content text,
  similarity float
)
LANGUAGE plpgsql
SET search_path = 'public'
AS $$
BEGIN
  RETURN QUERY
  SELECT
    bc.id,
    bc.bylaw_id,
    bc.chunk_index,
    bc.text_content,
    1 - (bc.embedding <=> query_embedding) AS similarity
  FROM bylaw_chunks bc
  WHERE (filter_bylaw_id IS NULL OR bc.bylaw_id = filter_bylaw_id)
    AND 1 - (bc.embedding <=> query_embedding) > match_threshold
  ORDER BY bc.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

CREATE OR REPLACE FUNCTION match_key_statements (
  query_embedding halfvec(384),
  match_threshold float,
  match_count int
)
RETURNS TABLE (
  id bigint,
  meeting_id bigint,
  agenda_item_id bigint,
  speaker_name text,
  statement_type text,
  statement_text text,
  context text,
  similarity float
)
LANGUAGE plpgsql
SET search_path = 'public'
AS $$
BEGIN
  RETURN QUERY
  SELECT
    ks.id, ks.meeting_id, ks.agenda_item_id, ks.speaker_name,
    ks.statement_type, ks.statement_text, ks.context,
    1 - (ks.embedding <=> query_embedding) AS similarity
  FROM key_statements ks
  WHERE 1 - (ks.embedding <=> query_embedding) > match_threshold
  ORDER BY ks.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

COMMENT ON FUNCTION match_motions IS 'Semantic similarity search for motions.';
COMMENT ON FUNCTION match_matters IS 'Semantic similarity search for matters.';
COMMENT ON FUNCTION match_agenda_items IS 'Semantic similarity search for agenda items.';
COMMENT ON FUNCTION match_bylaws IS 'Semantic similarity search for bylaws.';
COMMENT ON FUNCTION match_bylaw_chunks IS 'Semantic similarity search for bylaw segments.';
COMMENT ON FUNCTION match_key_statements IS 'Semantic similarity search for key statements.';
